import { IMovieDetailsResponse } from '../interfaces/responses/movie-details/movie-details-response.interface';

export const mockMovieDetailsResponse: IMovieDetailsResponse = {
  adult: false,
  backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
  belongs_to_collection: null,
  budget: 200000000,
  genres: [
    {
      id: 28,
      name: 'Action',
    },
    {
      id: 14,
      name: 'Fantasy',
    },
    {
      id: 878,
      name: 'Science Fiction',
    },
  ],
  homepage: 'https://www.dc.com/BlackAdam',
  id: 436270,
  imdb_id: 'tt6443346',
  original_language: 'en',
  original_title: 'Black Adam',
  overview:
    'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
  popularity: 17020.709,
  poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
  production_companies: [
    {
      id: 12,
      logo_path: '/iaYpEp3LQmb8AfAtmTvpqd4149c.png',
      name: 'New Line Cinema',
      origin_country: 'US',
    },
    {
      id: 34081,
      logo_path: null,
      name: 'Flynn Picture Company',
      origin_country: 'US',
    },
    {
      id: 73669,
      logo_path: '/7tmSGstK3KwgcDIuBYLTAayjit9.png',
      name: 'Seven Bucks Productions',
      origin_country: 'US',
    },
    {
      id: 128064,
      logo_path: '/13F3Jf7EFAcREU0xzZqJnVnyGXu.png',
      name: 'DC Films',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {
      iso_3166_1: 'US',
      name: 'United States of America',
    },
  ],
  release_date: '2022-10-19',
  revenue: 351000000,
  runtime: 125,
  spoken_languages: [
    {
      english_name: 'Danish',
      iso_639_1: 'da',
      name: 'Dansk',
    },
    {
      english_name: 'English',
      iso_639_1: 'en',
      name: 'English',
    },
  ],
  status: 'Released',
  tagline: 'The world needed a hero. It got Black Adam.',
  title: 'Black Adam',
  video: false,
  vote_average: 6.839,
  vote_count: 1237,
  similar: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: '/4svggv4gfe6vHsrGpaRMzrXLozt.jpg',
        genre_ids: [80, 35, 10402, 53],
        id: 299,
        original_language: 'en',
        original_title: "Ocean's Eleven",
        overview:
          'Danny Ocean and his gang attempt to rob the five biggest casinos in Las Vegas in one night.',
        popularity: 11.289,
        poster_path: '/A4R6u7SidBPVXMVzGSysCiRGTRz.jpg',
        release_date: '1960-08-10',
        title: "Ocean's Eleven",
        video: false,
        vote_average: 6.445,
        vote_count: 262,
      },
      {
        adult: false,
        backdrop_path: '/eCebbqmTsIiKJDSsjkr1BjgWDot.jpg',
        genre_ids: [28, 12, 37],
        id: 1656,
        original_language: 'en',
        original_title: 'The Legend of Zorro',
        overview:
          "Having spent the last 10 years fighting injustice and cruelty, Alejandro de la Vega is now facing his greatest challenge: his loving wife Elena has thrown him out of the house!  Elena has filed for divorce and found comfort in the arms of Count Armand, a dashing French aristocrat.  But Alejandro knows something she doesn't: Armand is the evil mastermind behind a terrorist plot to destroy the United States.  And so, with his marriage and the county's future at stake, it's up to Zorro to save two unions before it's too late.",
        popularity: 22.727,
        poster_path: '/duZDsuIA2uX93Vujtm89oHeTFqE.jpg',
        release_date: '2005-10-24',
        title: 'The Legend of Zorro',
        video: false,
        vote_average: 6.107,
        vote_count: 2510,
      },
      {
        adult: false,
        backdrop_path: '/cyecB7godJ6kNHGONFjUyVN9OX5.jpg',
        genre_ids: [28, 878, 12],
        id: 1726,
        original_language: 'en',
        original_title: 'Iron Man',
        overview:
          'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
        popularity: 124.807,
        poster_path: '/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
        release_date: '2008-04-30',
        title: 'Iron Man',
        video: false,
        vote_average: 7.6,
        vote_count: 23528,
      },
      {
        adult: false,
        backdrop_path: '/8OAuQm5Bxg4k4HIYfmcga5rYSzU.jpg',
        genre_ids: [28, 878, 53],
        id: 1738,
        original_language: 'en',
        original_title: 'Next',
        overview:
          'Las Vegas showroom magician Cris Johnson has a secret which torments him: he can see a few minutes into the future. Sick of the examinations he underwent as a child and the interest of the government and medical establishment in his power, he lies low under an assumed name in Vegas, performing cheap tricks and living off small-time gambling "winnings." But when a terrorist group threatens to detonate a nuclear device in Los Angeles, government agent Callie Ferris must use all her wiles to capture Cris and convince him to help her stop the cataclysm.',
        popularity: 16.779,
        poster_path: '/td5uOBW41ib1KGz3g1Kc33BdFyj.jpg',
        release_date: '2007-04-25',
        title: 'Next',
        video: false,
        vote_average: 6.023,
        vote_count: 2516,
      },
      {
        adult: false,
        backdrop_path: '/yFuKvT4Vm3sKHdFY4eG6I4ldAnn.jpg',
        genre_ids: [28, 12, 878],
        id: 1771,
        original_language: 'en',
        original_title: 'Captain America: The First Avenger',
        overview:
          "During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort. Rogers must stop the Red Skull – Adolf Hitler's ruthless head of weaponry, and the leader of an organization that intends to use a mysterious device of untold powers for world domination.",
        popularity: 86.489,
        poster_path: '/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg',
        release_date: '2011-07-22',
        title: 'Captain America: The First Avenger',
        video: false,
        vote_average: 7.0,
        vote_count: 19228,
      },
      {
        adult: false,
        backdrop_path: '/wM1aNIXSqB8GSeQY38LOUHYMYIw.jpg',
        genre_ids: [28, 12, 35, 878],
        id: 607,
        original_language: 'en',
        original_title: 'Men in Black',
        overview:
          'After a police chase with an otherworldly being, a New York City cop is recruited as an agent in a top-secret organization established to monitor and police alien activity on Earth: the Men in Black. Agent Kay and new recruit Agent Jay find themselves in the middle of a deadly plot by an intergalactic terrorist who has arrived on Earth to assassinate two ambassadors from opposing galaxies.',
        popularity: 45.955,
        poster_path: '/uLOmOF5IzWoyrgIF5MfUnh5pa1X.jpg',
        release_date: '1997-07-02',
        title: 'Men in Black',
        video: false,
        vote_average: 7.2,
        vote_count: 12046,
      },
      {
        adult: false,
        backdrop_path: '/9LSqKUrq1QTWf9wHic4lNOgw21K.jpg',
        genre_ids: [28, 12, 35, 878],
        id: 608,
        original_language: 'en',
        original_title: 'Men in Black II',
        overview:
          "Kay and Jay reunite to provide our best, last and only line of defense against a sinister seductress who levels the toughest challenge yet to the MIB's untarnished mission statement – protecting Earth from the scum of the universe. It's been four years since the alien-seeking agents averted an intergalactic disaster of epic proportions. Now it's a race against the clock as Jay must convince Kay – who not only has absolutely no memory of his time spent with the MIB, but is also the only living person left with the expertise to save the galaxy – to reunite with the MIB before the earth submits to ultimate destruction.",
        popularity: 39.378,
        poster_path: '/enA22EPyzc2WQ1VVyY7zxresQQr.jpg',
        release_date: '2002-07-03',
        title: 'Men in Black II',
        video: false,
        vote_average: 6.351,
        vote_count: 8670,
      },
      {
        adult: false,
        backdrop_path: '/1Gci6i2RHuum4JaXnlWfev3GH5b.jpg',
        genre_ids: [9648, 53, 18],
        id: 617,
        original_language: 'en',
        original_title: 'Wild Things',
        overview:
          "When teen-socialite Kelly Van Ryan and troubled bad girl Suzie Toller accuse guidance counselor Sam Lombardo of rape, he's suspended by the school, rejected by the town, and fighting to get his life back. One cop suspects conspiracy, but nothing is what it seems...",
        popularity: 21.333,
        poster_path: '/aaicreJBf7EuwGq3GgUV5ZedlfF.jpg',
        release_date: '1998-03-20',
        title: 'Wild Things',
        video: false,
        vote_average: 6.344,
        vote_count: 1407,
      },
      {
        adult: false,
        backdrop_path: '/c6yfABGVKuB5cjoOwdX4AJMlzUz.jpg',
        genre_ids: [35, 14],
        id: 620,
        original_language: 'en',
        original_title: 'Ghostbusters',
        overview:
          'After losing their academic posts at a prestigious university, a team of parapsychologists goes into business as proton-pack-toting "ghostbusters" who exterminate ghouls, hobgoblins and supernatural pests of all stripes. An ad campaign pays off when a knockout cellist hires the squad to purge her swanky digs of demons that appear to be living in her refrigerator.',
        popularity: 27.903,
        poster_path: '/hUEPftnbf78v2LdQZA7qDsnK1R5.jpg',
        release_date: '1984-06-08',
        title: 'Ghostbusters',
        video: false,
        vote_average: 7.5,
        vote_count: 7631,
      },
      {
        adult: false,
        backdrop_path: '/ijZKFKzppG2GxGAQhJmyhKNw1wJ.jpg',
        genre_ids: [9648, 53, 27],
        id: 622,
        original_language: 'en',
        original_title: 'The Ninth Gate',
        overview:
          "An all-expenses-paid international search for a rare copy of the book 'The Nine Gates of the Kingdom  of Shadows' brings an unscrupulous book dealer deep into a world of murder, double-dealing and satanic worship.",
        popularity: 15.044,
        poster_path: '/rxw9l9YNL14ODdmAavUwHLBjiDo.jpg',
        release_date: '1999-08-25',
        title: 'The Ninth Gate',
        video: false,
        vote_average: 6.446,
        vote_count: 2443,
      },
      {
        adult: false,
        backdrop_path: '/e9GbzPawXDFvLwSseCXpHkbCyAP.jpg',
        genre_ids: [18, 80],
        id: 627,
        original_language: 'en',
        original_title: 'Trainspotting',
        overview:
          "Heroin addict Mark Renton stumbles through bad ideas and sobriety attempts with his unreliable friends -- Sick Boy, Begbie, Spud and Tommy. He also has an underage girlfriend, Diane, along for the ride. After cleaning up and moving from Edinburgh to London, Mark finds he can't escape the life he left behind when Begbie shows up at his front door on the lam, and a scheming Sick Boy follows.",
        popularity: 22.458,
        poster_path: '/bhY62Dw8iW54DIhxPQerbuB9DOP.jpg',
        release_date: '1996-02-23',
        title: 'Trainspotting',
        video: false,
        vote_average: 7.97,
        vote_count: 8467,
      },
      {
        adult: false,
        backdrop_path: '/imvV078HyWsa9jgDVLi4APgskrJ.jpg',
        genre_ids: [35, 10749, 18],
        id: 634,
        original_language: 'en',
        original_title: "Bridget Jones's Diary",
        overview:
          'A chaotic Bridget Jones meets a snobbish lawyer, and he soon enters her world of imperfections.',
        popularity: 21.623,
        poster_path: '/dkauRl9TosBFikftrC3OVcKWDoz.jpg',
        release_date: '2001-04-13',
        title: "Bridget Jones's Diary",
        video: false,
        vote_average: 6.752,
        vote_count: 4354,
      },
      {
        adult: false,
        backdrop_path: '/eUl0JExl11ZyAgNjwxXzdIXlQlE.jpg',
        genre_ids: [27, 9648],
        id: 635,
        original_language: 'en',
        original_title: 'Angel Heart',
        overview:
          'Down-and-out private detective Harry Angel is ordered by the mysterious Louis Cyphre to go on a mission to find a missing person. His routine failure soon leads to a bloody spar with himself, as he goes on a supernatural journey into his own soul.',
        popularity: 13.549,
        poster_path: '/xKnJ4drN6J4dTu7E0yoBqrRALG2.jpg',
        release_date: '1987-03-06',
        title: 'Angel Heart',
        video: false,
        vote_average: 7.109,
        vote_count: 1224,
      },
      {
        adult: false,
        backdrop_path: '/8uNjWHsSW3TSOWDU4EY76H5MzAG.jpg',
        genre_ids: [28, 53, 12],
        id: 657,
        original_language: 'en',
        original_title: 'From Russia with Love',
        overview:
          'Agent 007 is back in the second installment of the James Bond series, this time battling a secret crime organization known as SPECTRE. Russians Rosa Klebb and Kronsteen are out to snatch a decoding device known as the Lektor, using the ravishing Tatiana to lure Bond into helping them. Bond willingly travels to meet Tatiana in Istanbul, where he must rely on his wits to escape with his life in a series of deadly encounters with the enemy.',
        popularity: 28.41,
        poster_path: '/2jUOA4mUm2W7jP61DFeZ77kH0sA.jpg',
        release_date: '1963-10-10',
        title: 'From Russia with Love',
        video: false,
        vote_average: 7.07,
        vote_count: 2453,
      },
      {
        adult: false,
        backdrop_path: '/lh65Y0sUQcRh5UVVgnTOfMUbN2c.jpg',
        genre_ids: [12, 28, 53],
        id: 658,
        original_language: 'en',
        original_title: 'Goldfinger',
        overview:
          "Special agent 007 comes face to face with one of the most notorious villains of all time, and now he must outwit and outgun the powerful tycoon to prevent him from cashing in on a devious scheme to raid Fort Knox -- and obliterate the world's economy.",
        popularity: 27.411,
        poster_path: '/6fTzum7gSpLWww26WvWjETNqfD9.jpg',
        release_date: '1964-09-20',
        title: 'Goldfinger',
        video: false,
        vote_average: 7.346,
        vote_count: 2989,
      },
      {
        adult: false,
        backdrop_path: '/sFEYsEfzTx7hhjetlNrme8B5OUo.jpg',
        genre_ids: [28, 53, 878],
        id: 752,
        original_language: 'en',
        original_title: 'V for Vendetta',
        overview:
          'In a world in which Great Britain has become a fascist state, a masked vigilante known only as “V” conducts guerrilla warfare against the oppressive British government. When V rescues a young woman from the secret police, he finds in her an ally with whom he can continue his fight to free the people of Britain.',
        popularity: 46.705,
        poster_path: '/1avD1JeaRiJX5M4ahPdZPypGoGN.jpg',
        release_date: '2006-02-23',
        title: 'V for Vendetta',
        video: false,
        vote_average: 7.901,
        vote_count: 12715,
      },
      {
        adult: false,
        backdrop_path: '/xo2S7gRwCvWdVqM0Swv37yA2rzw.jpg',
        genre_ids: [27, 9648, 53],
        id: 768,
        original_language: 'en',
        original_title: 'From Hell',
        overview:
          "Frederick Abberline is an opium-huffing inspector from Scotland Yard who falls for one of Jack the Ripper's prostitute targets in this Hughes brothers adaption of a graphic novel that posits the Ripper's true identity.",
        popularity: 23.575,
        poster_path: '/t2WpWM8nBO4sULXr2bDfNEt4qgr.jpg',
        release_date: '2001-02-08',
        title: 'From Hell',
        video: false,
        vote_average: 6.694,
        vote_count: 2402,
      },
      {
        adult: false,
        backdrop_path: '/xIUllvT7at1ua65O2HT7MUA9pVk.jpg',
        genre_ids: [27],
        id: 806,
        original_language: 'en',
        original_title: 'The Omen',
        overview:
          'A diplomatic couple adopts the son of the devil without knowing it. A remake of the classic horror film of the same name from 1976.',
        popularity: 22.78,
        poster_path: '/kf1Qq9b32jn4umll9qD2ue5ftnh.jpg',
        release_date: '2006-06-06',
        title: 'The Omen',
        video: false,
        vote_average: 5.6,
        vote_count: 884,
      },
      {
        adult: false,
        backdrop_path: '/wxkXCVGw61kbJAfP9SkxoETD0uz.jpg',
        genre_ids: [14, 12, 16, 35, 10751],
        id: 810,
        original_language: 'en',
        original_title: 'Shrek the Third',
        overview:
          'The King of Far Far Away has died and Shrek and Fiona are to become King & Queen. However, Shrek wants to return to his cozy swamp and live in peace and quiet, so when he finds out there is another heir to the throne, they set off to bring him back to rule the kingdom.',
        popularity: 123.465,
        poster_path: '/jaNe16gE9zdAYyVwRqmlmRKshHm.jpg',
        release_date: '2007-05-17',
        title: 'Shrek the Third',
        video: false,
        vote_average: 6.271,
        vote_count: 7678,
      },
      {
        adult: false,
        backdrop_path: '/3tSCdgdUpXmkpHtAoQJgTt1LSI0.jpg',
        genre_ids: [878, 35, 80],
        id: 816,
        original_language: 'en',
        original_title: 'Austin Powers: International Man of Mystery',
        overview:
          "As a swingin' fashion photographer by day and a groovy British superagent by night, Austin Powers is the '60s' most shagadelic spy, baby! But can he stop megalomaniac Dr. Evil after the bald villain freezes himself and unthaws in the '90s? With the help of sexy sidekick Vanessa Kensington, he just might.",
        popularity: 21.61,
        poster_path: '/5uD4dxNX8JKFjWKYMHyOsqhi5pN.jpg',
        release_date: '1997-05-02',
        title: 'Austin Powers: International Man of Mystery',
        video: false,
        vote_average: 6.537,
        vote_count: 2844,
      },
    ],
    total_pages: 500,
    total_results: 10000,
  },
  account_states: {
    favorite: false,
    rated: false,
    watchlist: false,
  },
  recommendations: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: '/y5Z0WesTjvn59jP6yo459eUsbli.jpg',
        id: 663712,
        title: 'Terrifier 2',
        original_language: 'en',
        original_title: 'Terrifier 2',
        overview:
          "After being resurrected by a sinister entity, Art the Clown returns to Miles County where he must hunt down and destroy a teenage girl and her younger brother on Halloween night.  As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",
        poster_path: '/b6IRp6Pl2Fsq37r9jFhGoLtaqHm.jpg',
        media_type: 'movie',
        genre_ids: [27, 53],
        popularity: 2735.525,
        release_date: '2022-10-06',
        video: false,
        vote_average: 6.969,
        vote_count: 637,
      },
      {
        adult: false,
        backdrop_path: '/mqsPyyeDCBAghXyjbw4TfEYwljw.jpg',
        id: 49046,
        title: 'All Quiet on the Western Front',
        original_language: 'de',
        original_title: 'Im Westen nichts Neues',
        overview:
          'Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.',
        poster_path: '/hYqOjJ7Gh1fbqXrxlIao1g8ZehF.jpg',
        media_type: 'movie',
        genre_ids: [10752, 18, 28],
        popularity: 1469.082,
        release_date: '2022-10-07',
        video: false,
        vote_average: 7.806,
        vote_count: 856,
      },
      {
        adult: false,
        backdrop_path: null,
        id: 642721,
        title: 'Awdat Al-Rouh',
        original_language: 'ar',
        original_title: 'Awdat Al-Rouh',
        overview: '',
        poster_path: '/mOpHGETnYr1OgQifBb7xk59N5Il.jpg',
        media_type: 'movie',
        genre_ids: [],
        popularity: 0.916,
        release_date: '',
        video: false,
        vote_average: 0.0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: '/xKCpH9xF4JReTL5NsWm4wtafPQP.jpg',
        id: 963954,
        title: '123 Hugs',
        original_language: 'en',
        original_title: '123 Peluk',
        overview: 'If hugs are tangible why am I hugging the void',
        poster_path: '/lfgmWyWWV3WPJ53jxWUQa3NtJ8f.jpg',
        media_type: 'movie',
        genre_ids: [],
        popularity: 0.956,
        release_date: '2022-05-11',
        video: false,
        vote_average: 7.0,
        vote_count: 1,
      },
      {
        adult: false,
        backdrop_path: null,
        id: 365297,
        title: 'My Chemical Romance: AOL Sessions',
        original_language: 'en',
        original_title: 'My Chemical Romance: AOL Sessions',
        overview:
          "AOL Sessions is a video release of the live Sessions@AOL performances by American rock band My Chemical Romance. The album features six videos, all of which are songs from the band's third studio album, The Black Parade.",
        poster_path: '/iqoNZKyfqUMRKKo0VZOaGyMrF9g.jpg',
        media_type: 'movie',
        genre_ids: [10402],
        popularity: 0.688,
        release_date: '2007-12-18',
        video: true,
        vote_average: 10.0,
        vote_count: 2,
      },
      {
        adult: false,
        backdrop_path: null,
        id: 887731,
        title: 'Back Home',
        original_language: 'ar',
        original_title: 'Al Awda',
        overview:
          'Due to the impact of the global Coronavirus pandemic, the author of the film comes back to her birthplace after having spent the last 10 years abroad. She goes about her daily routine under lockdown along with her parents: her father teeming with good humour who takes government restrictions with reservations, and her mother who voluntarily locks herself in her room because of fears she could infect other flatmates with the virus she may not even have. Sara Shazli observes city bustle outside the windows and domestic life through the camera lens in her own perspective, treating familiar situations with both tragic and comic distance. Being locked down with her parents helps her in rediscovering family ties and her relationship to home.',
        poster_path: null,
        media_type: 'movie',
        genre_ids: [99],
        popularity: 0.6,
        release_date: '2021-10-21',
        video: false,
        vote_average: 0.0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: '/ySHlkHDbXztjdjRJ0pZN7FXRnaW.jpg',
        id: 631132,
        title: "Goblin Slayer: Goblin's Crown",
        original_language: 'ja',
        original_title: "ゴブリンスレイヤー -GOBLIN'S CROWN-",
        overview:
          'Goblin Slayer and his party head up to the snowy mountains in the north after receiving that request from the Sword Maiden to find any information on the Noble Fencer that disappeared after leaving to slay some goblins. A small village gets attacked, they encounter a mysterious chapel, and something about how these goblins are acting bothers the Goblin slayer.  In order to save the captured Noble Fencer, the Goblin Slayer and his party head to an ancient fortress covered in snow to face off with a powerful foe and a horde of goblins!',
        poster_path: '/oyDaF4za9C9GxfYSyZUmj2aZGJT.jpg',
        media_type: 'movie',
        genre_ids: [16, 12, 28, 14],
        popularity: 87.861,
        release_date: '2020-02-01',
        video: false,
        vote_average: 7.6,
        vote_count: 174,
      },
      {
        adult: false,
        backdrop_path: '/etP5jwlwvkNhwe7jnI2AyA6ZKrR.jpg',
        id: 575322,
        title: 'Project Gemini',
        original_language: 'en',
        original_title: 'Звёздный разум',
        overview:
          "After depleting Earth's resources for centuries, humankind's survival requires an exodus to outer space. An international expedition is quickly formed to find a suitable new planet, but when plans go awry, the crew is suddenly stranded without power on a strange planet, where something unimaginable lies in wait.",
        poster_path: '/rFljUdOozFEv6HDHIFpFvcYW0ec.jpg',
        media_type: 'movie',
        genre_ids: [878],
        popularity: 1006.951,
        release_date: '2022-01-06',
        video: false,
        vote_average: 5.657,
        vote_count: 169,
      },
      {
        adult: false,
        backdrop_path: '/1UlTowc5vfrgXUVT6OnlU0TOiij.jpg',
        id: 616820,
        title: 'Halloween Ends',
        original_language: 'en',
        original_title: 'Halloween Ends',
        overview:
          'Four years after the events of Halloween in 2018, Laurie has decided to liberate herself from fear and rage and embrace life. But when a young man is accused of killing a boy he was babysitting, it ignites a cascade of violence and terror that will force Laurie to finally confront the evil she can’t control, once and for all.',
        poster_path: '/yoAKHpveZ4Z1wwwXoD31dXj3H8s.jpg',
        media_type: 'movie',
        genre_ids: [27, 53],
        popularity: 626.112,
        release_date: '2022-10-12',
        video: false,
        vote_average: 6.502,
        vote_count: 957,
      },
      {
        adult: false,
        backdrop_path: '/2SEGjVLy7fYbovIyDR7IntH1jT2.jpg',
        id: 913290,
        title: 'Barbarian',
        original_language: 'en',
        original_title: 'Barbarian',
        overview:
          'In town for a job interview, a young woman arrives at her Airbnb late at night only to find that it has been mistakenly double-booked and a strange man is already staying there. Against her better judgement, she decides to stay the night anyway, but soon discovers that there is much more to be afraid of in the house than the other guest.',
        poster_path: '/idT5mnqPcJgSkvpDX7pJffBzdVH.jpg',
        media_type: 'movie',
        genre_ids: [27, 53],
        popularity: 372.823,
        release_date: '2022-09-08',
        video: false,
        vote_average: 6.959,
        vote_count: 756,
      },
      {
        adult: false,
        backdrop_path: '/wizYHZzSr0wJmB3Oo6LTFaP4HzY.jpg',
        id: 707103,
        title: 'Emily',
        original_language: 'en',
        original_title: 'Emily',
        overview:
          'The imagined life of one of the world’s most famous authors, Emily Brontë, as she finds her voice and writes the literary classic Wuthering Heights. Explore the relationships that inspired her – her raw, passionate sisterhood with Charlotte and Anne; her first aching, forbidden love for Weightman and her care for her maverick brother whom she idolises.',
        poster_path: '/tgVBMIiJczfBWINRRd9yxE8ESln.jpg',
        media_type: 'movie',
        genre_ids: [18, 36, 10749],
        popularity: 23.523,
        release_date: '2022-10-14',
        video: false,
        vote_average: 7.0,
        vote_count: 12,
      },
      {
        adult: false,
        backdrop_path: '/frLvNMm25SlmvEZM8hlhYKBkGoS.jpg',
        id: 674324,
        title: 'The Banshees of Inisherin',
        original_language: 'en',
        original_title: 'The Banshees of Inisherin',
        overview:
          'Two lifelong friends find themselves at an impasse when one abruptly ends their relationship, with alarming consequences for both of them.',
        poster_path: '/dpeR3ue0Q93Rk8jhE2DzVPMRGIm.jpg',
        media_type: 'movie',
        genre_ids: [18, 35],
        popularity: 26.802,
        release_date: '2022-10-21',
        video: false,
        vote_average: 8.2,
        vote_count: 47,
      },
      {
        adult: false,
        backdrop_path: '/tIX6j3NzadlwGcJ52nuWdmtOQkg.jpg',
        id: 717728,
        title: 'Jeepers Creepers: Reborn',
        original_language: 'en',
        original_title: 'Jeepers Creepers: Reborn',
        overview:
          'Forced to travel with her boyfriend to a horror festival, Laine begins to experience disturbing visions associated with the urban legend of The Creeper. As the festival arrives and the blood-soaked entertainment builds to a frenzy, she becomes the center of it while something unearthly has been summoned.',
        poster_path: '/qVVegwPsW6n9unBtLWq1rzOutka.jpg',
        media_type: 'movie',
        genre_ids: [27, 53, 9648],
        popularity: 2047.345,
        release_date: '2022-09-15',
        video: false,
        vote_average: 5.8,
        vote_count: 473,
      },
      {
        adult: false,
        backdrop_path: null,
        id: 1038976,
        title: 'Trail of the Kiamichi Beast',
        original_language: 'en',
        original_title: 'Trail of the Kiamichi Beast',
        overview:
          'A TRUE story  a beast in  Oklahoma and Arkansas Ouachita forests. The locals want this legend buried. to be kept a secret. Trail of the Kiamichi beast brings even more evidence to light following the stunning exposure in  the movies ‘ The Kiamichi beast expedition and the Kiamichi beast expedition 2, which exposed stunning proof of Bigfoot in Oklahoma',
        poster_path: '/yo26axYjP5ti9i0ZXgHfnFz86dj.jpg',
        media_type: 'movie',
        genre_ids: [12, 14, 27],
        popularity: 2.041,
        release_date: '2022-10-30',
        video: false,
        vote_average: 3.5,
        vote_count: 1,
      },
      {
        adult: false,
        backdrop_path: null,
        id: 361951,
        title: 'Bezango, WA',
        original_language: 'en',
        original_title: 'Bezango, WA',
        overview:
          'Bezango, WA tells the tale of cartooning and comics in the Pacific Northwest, focusing on the alternative community. The film chronicles both the past and the present, while featuring Frank M. Young, co-creator of the Eisner Award winning graphic novel "The Carter Family: Don\'t Forget This Song," and James Gill, a cartoonist, and mostly-cheerful introvert of the finest class.',
        poster_path: '/9wPpY50KgW94Ozy3jwDWYdo0jBu.jpg',
        media_type: 'movie',
        genre_ids: [99],
        popularity: 1.127,
        release_date: '2015-09-30',
        video: false,
        vote_average: 3.5,
        vote_count: 3,
      },
      {
        adult: false,
        backdrop_path: '/faek7NPiZqTZhstTfLQG1saw08D.jpg',
        id: 768744,
        title: "My Hero Academia: World Heroes' Mission",
        original_language: 'ja',
        original_title:
          '僕のヒーローアカデミア THE MOVIE ワールド ヒーローズ ミッション',
        overview:
          'A mysterious group called Humarize strongly believes in the Quirk Singularity Doomsday theory which states that when quirks get mixed further in with future generations, that power will bring forth the end of humanity. In order to save everyone, the Pro-Heroes around the world ask UA Academy heroes-in-training to assist them and form a world-class selected hero team. It’s up to the heroes to save the world and the future of heroes in what is the most dangerous crisis to take place yet in My Hero Academia.',
        poster_path: '/AsTlA7dj2ySGY1pzGSD0MoHFhEF.jpg',
        media_type: 'movie',
        genre_ids: [16, 28, 12, 878],
        popularity: 398.629,
        release_date: '2021-08-06',
        video: false,
        vote_average: 7.633,
        vote_count: 315,
      },
      {
        adult: false,
        backdrop_path: '/5hoS3nEkGGXUfmnu39yw1k52JX5.jpg',
        id: 960704,
        title: 'Fullmetal Alchemist: The Final Alchemy',
        original_language: 'ja',
        original_title: '鋼の錬金術師 完結編 最後の錬成',
        overview:
          'The Elric brothers’ long and winding journey comes to a close in this epic finale, where they must face off against an unworldly, nationwide threat.',
        poster_path: '/AeyiuQUUs78bPkz18FY3AzNFF8b.jpg',
        media_type: 'movie',
        genre_ids: [28, 12, 14],
        popularity: 1021.716,
        release_date: '2022-06-24',
        video: false,
        vote_average: 6.325,
        vote_count: 120,
      },
      {
        adult: false,
        backdrop_path: null,
        id: 344708,
        title: 'Singham 123',
        original_language: 'te',
        original_title: 'Singham 123',
        overview:
          'Singham 123 is a spoof action comedy starring Sampoornesh Babu playing the role of a "Sensational", "Seductive", "Supercop". Set in the backdrop of a village called Singarayakonda which is ruled by a self proclaimed king and mafia-lord, Lingham. He fancies himself as the destructive force and an archenemy of Law and Order. After several failed attempts by Indian Police throughout the decade, Singham123 is assigned the mission impossible: to arrest Lingham. Will Singham 123 be successful in completing the mission?',
        poster_path: '/plJWXM4THCeOIlnCkd02X93cDzX.jpg',
        media_type: 'movie',
        genre_ids: [35, 28],
        popularity: 1.414,
        release_date: '2015-06-05',
        video: false,
        vote_average: 6.5,
        vote_count: 6,
      },
      {
        adult: false,
        backdrop_path: '/pGx6O6IwqADOsgmqWzPysmWnOyr.jpg',
        id: 732459,
        title: 'Blade of the 47 Ronin',
        original_language: 'en',
        original_title: 'Blade of the 47 Ronin',
        overview:
          'In this sequel to "47 Ronin," a new class of warriors emerges among the Samurai clans to keep a sought-after sword from falling into the wrong hands.',
        poster_path: '/kjFDIlUCJkcpFxYKtE6OsGcAfQQ.jpg',
        media_type: 'movie',
        genre_ids: [28, 14],
        popularity: 1299.891,
        release_date: '2022-10-25',
        video: false,
        vote_average: 6.925,
        vote_count: 80,
      },
      {
        adult: false,
        backdrop_path: '/mMA2YNddowV8MZtxpbn0a7Yilum.jpg',
        id: 928123,
        title: 'The Battle at Lake Changjin: Water Gate Bridge',
        original_language: 'zh',
        original_title: '长津湖之水门桥',
        overview:
          'In the follow-up to "The Battle At Lake Changjin", brothers Wu Qianli and Wu Wanli undertake a new task for the People\'s Volunteer Army, defending a bridge part of the American troops\' escape route from the advancing Chinese.',
        poster_path: '/ugiL6wIhl1OfPyv1gqLkTe45jLl.jpg',
        media_type: 'movie',
        genre_ids: [10752, 36, 28, 18],
        popularity: 689.69,
        release_date: '2022-02-01',
        video: false,
        vote_average: 6.6,
        vote_count: 25,
      },
      {
        adult: false,
        backdrop_path: '/bJa3RcFKgtVKJqTJCSSuBQeP9c8.jpg',
        id: 86328,
        title: 'Terrifier',
        original_language: 'en',
        original_title: 'Terrifier',
        overview:
          'After witnessing a brutal murder on Halloween night, a young woman becomes the next target of a maniacal entity.',
        poster_path: '/gb6rq2nD0jRrN0dCzigg2MxXNsB.jpg',
        media_type: 'movie',
        genre_ids: [27],
        popularity: 479.681,
        release_date: '2011-08-09',
        video: false,
        vote_average: 6.66,
        vote_count: 47,
      },
    ],
    total_pages: 2,
    total_results: 40,
  },
  reviews: {
    page: 1,
    results: [
      {
        author: 'MSB',
        author_details: {
          name: 'MSB',
          username: 'msbreviews',
          avatar_path:
            '/https://www.gravatar.com/avatar/992eef352126a53d7e141bf9e8707576.jpg',
          rating: 5.0,
        },
        content:
          'FULL SPOILER-FREE REVIEW @ https://www.msbreviews.com/movie-reviews/black-adam-spoiler-free-review\r\n\r\n"Black Adam is far from impressive, being somewhat disappointing due to its formulaic, predictable screenplay when something different was anticipated.\r\n\r\nLorne Balfe\'s epic score and a magnificent cast - Dwayne Johnson, Aldis Hodge, and most remarkably Pierce Brosnan are phenomenal - try to elevate the decent action and visuals, but the moderate entertainment levels don\'t make up for the dated narrative structure.\r\n\r\nTiresomely heavy exposition, story with little to no creativity, and inconsistent humor make it impossible for the DCEU to take "the next step" in a truly impactful manner."\r\n\r\nRating: C+',
        created_at: '2022-10-19T15:58:22.495Z',
        id: '63501e9ed363e5007a664110',
        updated_at: '2022-10-19T15:58:22.580Z',
        url: 'https://www.themoviedb.org/review/63501e9ed363e5007a664110',
      },
      {
        author: 'Faraz Khan',
        author_details: {
          name: 'Faraz Khan',
          username: 'farazmushtaqk',
          avatar_path: '/3H7iyvGtmsHQFcKIoaC1PkjiPij.jpg',
          rating: 7.0,
        },
        content: "Well it wasn't disappointing...",
        created_at: '2022-10-22T15:27:07.309Z',
        id: '63540bcb2441820082f30903',
        updated_at: '2022-10-31T14:25:56.902Z',
        url: 'https://www.themoviedb.org/review/63540bcb2441820082f30903',
      },
      {
        author: 'Chris Sawin',
        author_details: {
          name: 'Chris Sawin',
          username: 'ChrisSawin',
          avatar_path:
            '/https://www.gravatar.com/avatar/bf3b87ecb40599290d764e6d73c86319.jpg',
          rating: 3.0,
        },
        content:
          'With a horrid script, lackluster performances, and a waste of potentially awesome characters, _Black Adam_ is an explosive, $195 million, anti-heroic dud. The DCEU is about to get way more convoluted and underwhelming than ever before if this is the future of live action DC films.\r\n\r\n**Full review:** https://hubpages.com/entertainment/Black-Adam-20220-Review-A-Stale-and-Disjointed-Antihero-Kerfuffle',
        created_at: '2022-10-23T03:17:59.235Z',
        id: '6354b267c9dbf9008237a4b1',
        updated_at: '2022-10-23T03:17:59.339Z',
        url: 'https://www.themoviedb.org/review/6354b267c9dbf9008237a4b1',
      },
      {
        author: 'mooney240',
        author_details: {
          name: '',
          username: 'mooney240',
          avatar_path: '/blEC280vq31MVaDcsWBXuGOsYnB.jpg',
          rating: 8.0,
        },
        content:
          '**Black Adam might not reinvent the wheel, but it doesn’t have to. It just wants to take you on a fun, entertaining, exciting superhero ride!**\r\n\r\nBlack Adam has its haters, and I can understand why. It doesn’t necessarily break new ground in the superhero genre, but that doesn’t stop it from being awesome! Action-packed from start to finish. The effects are incredible. I kept myself from saying Wow out loud on multiple occasions. Dwayne Johnson’s Black Adam is absolutely ruthless, ripping armies of henchmen with ease and speed. I was worried a PG-13 rating might soften his brutality, but it did not! The action sequences looked amazing and were well done. I really liked the Justice Society characters, although they all felt a little stereotypical with a SpiderMan jokester, a wise old Professor X, and a quipping leader in the vain of Wolverine or Deadshot. Pierce Brosnan was perfect at Dr. Fate, making me wish he hadn’t been relegated to special guest star status. The movie didn’t waste a ton of time giving background on each character which was wise with so many new heroes on screen. The film had its moments of cheese but didn’t overdo it. Definitely watch the mid-credit scene. It’s stupendous! Black Adam was a fine addition to the superhero genre, and I look forward to what comes next.',
        created_at: '2022-10-23T04:48:53.283Z',
        id: '6354c7b5a843c1007d88ed93',
        updated_at: '2022-10-23T04:48:53.357Z',
        url: 'https://www.themoviedb.org/review/6354c7b5a843c1007d88ed93',
      },
      {
        author: 'jwilliams0511971',
        author_details: {
          name: '',
          username: 'jwilliams0511971',
          avatar_path: '/o0UldhElrSrizta5lSWb8ya8GtG.png',
          rating: 8.0,
        },
        content:
          "> _\"My powers are not a gift. They're a curse, born out of rage.\"_\r\n\r\nI had a blast watching this in theaters. This was very bombastic, with a lot of cool action, but also telling a heartfelt story about Black Adam.\r\n\r\nIt was very inventive how they depicted Black Adam's origin, keeping it a mystery up near the end. Dwayne Johnson was born to play Black Adam. He steals every scene he's in playing a badass anto-hero.\r\n\r\nNow the Justice Society, while they didn't have a backstory in the film, they each had prequel comics detailing their backstory. Which I really dig, these comics are meant to sell comics, after all. Might as well get the audience to buy the comics to get into some great stories (they are also currently doing this with The Flash). The movie actually starts right where the Doctor Fate prequel comic ends, so I don't think it's apographa. Doctor Fate played by Pierce Brosnan was a standout. He really put his all into this character. Aldis Hodge was also a standout as Hawkman.\r\n\r\nThe surprise villain of Black Adam, Sabbac, was a really good addition to the Shazam! mythos. If the wizards have their own champion, why doesn't the seven deadly sins have one? Sabbac is the answer to that. Doctor Fate's battle with him was really cool.\r\n\r\nOverall, this wasn't as bad as the critics were saying, I had a fun time! Be sure to stay for the mid-credits scene!",
        created_at: '2022-10-24T02:11:46.746Z',
        id: '6355f462f8e98200817bfb30',
        updated_at: '2022-10-31T14:26:08.218Z',
        url: 'https://www.themoviedb.org/review/6355f462f8e98200817bfb30',
      },
      {
        author: 'shamxal',
        author_details: {
          name: '',
          username: 'shamxal',
          avatar_path: null,
          rating: 0.5,
        },
        content: 'cool movie',
        created_at: '2022-10-24T07:08:55.360Z',
        id: '63563a07a06efe007a657d0c',
        updated_at: '2022-10-31T14:26:31.937Z',
        url: 'https://www.themoviedb.org/review/63563a07a06efe007a657d0c',
      },
      {
        author: 'CinemaSerf',
        author_details: {
          name: 'CinemaSerf',
          username: 'Geronimo1967',
          avatar_path: '/1kks3YnVkpyQxzw36CObFPvhL5f.jpg',
          rating: 6.0,
        },
        content:
          'In search of the all powerful crown of "Sabbac", "Adrianna" (Sarah Shahi) unleashes "Seth-Adam" (Dwayne Johnson) from his mountain-encased tomb deep in the desert. With super-human powers akin to "Superman", he returns to his home city of "Kahndaq" which is under the control of the "Intergangs". Will he decide to help her and her son "Amon" (Bodhi Sabongui) free them from this criminal tyranny? Well what nobody had counted on are the folks from the Justice League/Brotherhood/Department - led by "Hawkman" (Aldis Hodge) and "Dr. Fate" (Pierce Brosnan) who have decided that "Adam" is a bit of an wrong-un and so bring their state-of-the-art rocket ship as well as the "Atom Smasher" (Noah Centineo) and "Cyclone" (Quintessa Swindell) to capture or destroy him. Thing is, "Adam" is the stuff of legend to these people - reputedly having defeated an ancient despotic king - but is/was he all that he seemed? Is he good or evil or both? Well, to be honest I didn\'t really care. This is a very well produced and technically superb creative effort, but the story is all over the place and the repetitive combat scenes just grate after a while. Johnson has charisma, we have seen it loads of times, but here he exudes none. Hodge looks great in his winged-suit but again, his character is as deep as an Ethiopian river in July. Centineo has some fun as the giant - more than a passing resemblance to Mark Ruffalo, don\'t you think? Otherwise the rest of this is about as derivative as it comes. Hopefully this is just a one-off, as this is nobody\'s finest work and is up there with "Morbius" as a superhero film too many!',
        created_at: '2022-10-25T07:08:10.692Z',
        id: '63578b5aefd3c200907b78fd',
        updated_at: '2022-10-25T07:08:10.744Z',
        url: 'https://www.themoviedb.org/review/63578b5aefd3c200907b78fd',
      },
      {
        author: 'Nathan',
        author_details: {
          name: 'Nathan',
          username: 'TitanGusang',
          avatar_path: '/yHGV91jVzmqpFOtRSHF0avBZmPm.jpg',
          rating: 5.0,
        },
        content:
          '_Black Adam_ is in every aspect a generic superhero movie. There is nothing that really separates this for me, besides the body count that Black Adam stacks up during the film.\r\n\r\nOne thing I need to mention is the audio quality. So many lines of dialogue sound like they were recorded straight off from a cell phone. They do not match the scene at all and it was incredibly jarring throughout the entirety of the film. While I am talking about sound, in almost every fight scene the film included a badass rap song. It was cool the first time, but it got old and corny fast.\r\n\r\nThe plot was very generic from all aspects. It suffers by trying to catch the audience up in the first act. The film introduces the Justice Society and Black Adam and quickly accelerates the plot to start the main conflict of the film. It felt rushed and the conflict between the JSA and Black Adam was forced, nothing about it felt genuine. The villian in this movie was so forgettable, by the time he is introduced the conflict is over. I had zero emotional attachment to anyone in this movie. The dialogue was pretty bad as well, the scenes constantly switched from serious to comedy causing both aspects to fall flat for me.\r\n\r\nThe performances were okay, everyone was pretty average including Dwayne Johnson. Nothing spectacular and nothing bad enough for me to notice.\r\n\r\nOverall, I was excited for this new phase and direction of the DCEU and was left disappointed. Definitely one of the poorer movies in the franchise.\r\n\r\n**Score:** _48%_ |\r\n**Verdict:** _Average_',
        created_at: '2022-10-25T15:29:45.668Z',
        id: '635800e9d18fb9007ab4a9fe',
        updated_at: '2022-10-26T12:53:22.678Z',
        url: 'https://www.themoviedb.org/review/635800e9d18fb9007ab4a9fe',
      },
      {
        author: 'phutrong',
        author_details: {
          name: '',
          username: 'phutrong',
          avatar_path: null,
          rating: null,
        },
        content: 'Best DC Movie ever !!!',
        created_at: '2022-11-07T02:59:52.514Z',
        id: '636874a81684f7008aeb6249',
        updated_at: '2022-11-08T21:56:45.966Z',
        url: 'https://www.themoviedb.org/review/636874a81684f7008aeb6249',
      },
      {
        author: 'nhpro',
        author_details: {
          name: 'nhpro',
          username: 'nhpro100',
          avatar_path: null,
          rating: 10.0,
        },
        content: 'Very Good Movie',
        created_at: '2022-11-11T13:09:58.343Z',
        id: '636e49a621621b00b49e4502',
        updated_at: '2022-11-15T15:51:43.734Z',
        url: 'https://www.themoviedb.org/review/636e49a621621b00b49e4502',
      },
    ],
    total_pages: 1,
    total_results: 10,
  },
};
