import { Movie } from 'src/app/home/interfaces/movies.interface';

export const mockMoviesEntities: ImockMoviesEntities = {
  1: {
    adult: false,
    backdrop_path: '/y5Z0WesTjvn59jP6yo459eUsbli.jpg',
    genre_ids: [27, 53],
    id: 1,
    original_language: 'en',
    original_title: 'Terrifier 2',
    overview:
      "After being resurrected by a sinister entity, Art the Clown returns to Miles County where he must hunt down and destroy a teenage girl and her younger brother on Halloween night.  As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",
    popularity: 3803.184,
    poster_path: '/b6IRp6Pl2Fsq37r9jFhGoLtaqHm.jpg',
    release_date: '2022-10-06',
    title: 'Terrifier 2',
    video: false,
    vote_average: 7,
    vote_count: 563,
  },
  2: {
    adult: false,
    backdrop_path: '/8sMmAmN2x7mBiNKEX2o0aOTozEB.jpg',
    genre_ids: [28, 12, 878],
    id: 2,
    original_language: 'en',
    original_title: 'Black Panther: Wakanda Forever',
    overview:
      'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
    popularity: 3281.982,
    poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
    release_date: '2022-11-09',
    title: 'Black Panther: Wakanda Forever',
    video: false,
    vote_average: 7.6,
    vote_count: 347,
  },
  3: {
    adult: false,
    backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
    genre_ids: [28, 14, 878],
    id: 3,
    original_language: 'en',
    original_title: 'Black Adam',
    overview:
      'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
    popularity: 3779.941,
    poster_path: '/3zXceNTtyj5FLjwQXuPvLYK5YYL.jpg',
    release_date: '2022-10-19',
    title: 'Black Adam',
    video: false,
    vote_average: 6.9,
    vote_count: 1030,
  },
  4: {
    adult: false,
    backdrop_path: '/mqsPyyeDCBAghXyjbw4TfEYwljw.jpg',
    genre_ids: [10752, 18, 28],
    id: 4,
    original_language: 'de',
    original_title: 'Im Westen nichts Neues',
    overview:
      'Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.',
    popularity: 2642.131,
    poster_path: '/hYqOjJ7Gh1fbqXrxlIao1g8ZehF.jpg',
    release_date: '2022-10-07',
    title: 'All Quiet on the Western Front',
    video: false,
    vote_average: 7.9,
    vote_count: 687,
  },
  5: {
    adult: false,
    backdrop_path: '/u9Io1hVnxb2b3T0z99aOK8sq0SN.jpg',
    genre_ids: [9648, 12, 80],
    id: 5,
    original_language: 'en',
    original_title: 'Enola Holmes 2',
    overview:
      'Now a detective-for-hire like her infamous brother, Enola Holmes takes on her first official case to find a missing girl, as the sparks of a dangerous conspiracy ignite a mystery that requires the help of friends — and Sherlock himself — to unravel.',
    popularity: 3183.267,
    poster_path: '/tegBpjM5ODoYoM1NjaiHVLEA0QM.jpg',
    release_date: '2022-11-04',
    title: 'Enola Holmes 2',
    video: false,
    vote_average: 7.8,
    vote_count: 690,
  },
  6: {
    adult: false,
    backdrop_path: '/1DBDwevWS8OhiT3wqqlW7KGPd6m.jpg',
    genre_ids: [53],
    id: 6,
    original_language: 'en',
    original_title: 'Fall',
    overview:
      'For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights',
    popularity: 1661.901,
    poster_path: '/spCAxD99U1A6jsiePFoqdEcY0dG.jpg',
    release_date: '2022-08-11',
    title: 'Fall',
    video: false,
    vote_average: 7.3,
    vote_count: 1701,
  },
  7: {
    adult: false,
    backdrop_path: '/tIX6j3NzadlwGcJ52nuWdmtOQkg.jpg',
    genre_ids: [27, 53, 9648],
    id: 7,
    original_language: 'en',
    original_title: 'Jeepers Creepers: Reborn',
    overview:
      'Forced to travel with her boyfriend to a horror festival, Laine begins to experience disturbing visions associated with the urban legend of The Creeper. As the festival arrives and the blood-soaked entertainment builds to a frenzy, she becomes the center of it while something unearthly has been summoned.',
    popularity: 1486.45,
    poster_path: '/aGBuiirBIQ7o64FmJxO53eYDuro.jpg',
    release_date: '2022-09-15',
    title: 'Jeepers Creepers: Reborn',
    video: false,
    vote_average: 5.8,
    vote_count: 445,
  },
  8: {
    adult: false,
    backdrop_path: '/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
    genre_ids: [28, 18],
    id: 8,
    original_language: 'en',
    original_title: 'Top Gun: Maverick',
    overview:
      'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
    popularity: 1244.183,
    poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    release_date: '2022-05-24',
    title: 'Top Gun: Maverick',
    video: false,
    vote_average: 8.3,
    vote_count: 4697,
  },
  9: {
    adult: false,
    backdrop_path: '/yo0qfH2dQGGMxkfivdkz5zxVatD.jpg',
    genre_ids: [27, 53],
    id: 9,
    original_language: 'en',
    original_title: 'The Invitation',
    overview:
      'After the death of her mother, Evie is approached by an unknown cousin who invites her to a lavish wedding in the English countryside. Soon, she realizes a gothic conspiracy is afoot and must fight for survival as she uncovers twisted secrets in her family’s history.',
    popularity: 1350.879,
    poster_path: '/jcTq6gIskCsHlKDvCKKouEfiU66.jpg',
    release_date: '2022-08-24',
    title: 'The Invitation',
    video: false,
    vote_average: 6.4,
    vote_count: 306,
  },
  10: {
    adult: false,
    backdrop_path: '/Ach0puWzxuO2imh1yWEUK7CGsx.jpg',
    genre_ids: [16, 12, 28, 14],
    id: 10,
    original_language: 'ja',
    original_title: 'ONE PIECE FILM RED',
    overview:
      'Uta — the most beloved singer in the world. Her voice, which she sings with while concealing her true identity, has been described as “otherworldly.” She will appear in public for the first time at a live concert. As the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound.',
    popularity: 989.356,
    poster_path: '/m80kPdrmmtEh9wlLroCp0bwUGH0.jpg',
    release_date: '2022-08-06',
    title: 'One Piece Film Red',
    video: false,
    vote_average: 7.4,
    vote_count: 170,
  },
  11: {
    adult: false,
    backdrop_path: '/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg',
    genre_ids: [27, 53],
    id: 11,
    original_language: 'en',
    original_title: 'Orphan: First Kill',
    overview:
      'After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.',
    popularity: 1374.967,
    poster_path: '/pHkKbIRoCe7zIFvqan9LFSaQAde.jpg',
    release_date: '2022-07-27',
    title: 'Orphan: First Kill',
    video: false,
    vote_average: 6.8,
    vote_count: 1269,
  },
  12: {
    adult: false,
    backdrop_path: '/2iGUavwv86Hubv3V5Iq4qEQXDfE.jpg',
    genre_ids: [18, 53, 27],
    id: 12,
    original_language: 'es',
    original_title: 'Cerdita',
    overview:
      'A bullied overweight teenager sees a glimpse of hope when her tormentors are brutally abducted by a mesmerizing stranger.',
    popularity: 990.06,
    poster_path: '/8EIQAvJjXdbNDMmBtHtgGqbc09V.jpg',
    release_date: '2022-10-07',
    title: 'Piggy',
    video: false,
    vote_average: 6.7,
    vote_count: 186,
  },
};

type ImockMoviesEntities = { [n: number]: Movie };
export type mockMoviesKey = keyof ImockMoviesEntities;
