export enum SpecificMovieActionTypes {
  FETCH_DETAILS_START = '[Details Main Component] FETCH_DETAILS_START',
  FETCH_DETAILS_SUCCESS = '[Details Effects] FETCH_DETAILS_SUCCESS',
  FETCH_DETAILS_FAILURE = '[Details Effects] FETCH_DETAILS_FAILURE',
  FETCH_RECOMMENDED_START = '[Details Main Component] FETCH_RECOMMENDED_START',
  FETCH_RECOMMENDED_SUCCESS = '[Details Effects] FETCH_RECOMMENDED_SUCCESS',
  FETCH_RECOMMENDED_FAILURE = '[Details Effects] FETCH_RECOMMENDED_FAILURE',
  FETCH_SIMILAR_START = '[Details Main Component] FETCH_SIMILAR_START',
  FETCH_SIMILAR_SUCCESS = '[Details Effects] FETCH_SIMILAR_SUCCESS',
  FETCH_SIMILAR_FAILURE = '[Details Effects] FETCH_SIMILAR_FAILURE',
  CLEAR_SPECIFIC_MOVIES = '[Details effects] CLEAR_SPECIFIC_MOVIES',
  UPDATE_SPECIFIC_MOVIE_FAVORITE = '[Details effects] UPDATE_SPECIFIC_MOVIE_FAVORITE',
  UPDATE_ADD_MOVIE_RATE_SUCCESS = '[Details effects] UPDATE_ADD_MOVIE_RATE_SUCCESS',
  UPDATE_DELETE_MOVIE_RATE_SUCCESS = '[Details effects] UPDATE_DELETE_MOVIE_RATE_SUCCESS',
  UPDATE_SPECIFIC_MOVIE_WATCHLIST_SUCCESS = '[Details effects] UPDATE_SPECIFIC_MOVIE_WATCHLIST_SUCCESS',
  ADD_TO_WATCHLIST_START = '[Movie details movie ]ADD_TO_WATCHLIST_START',
  REMOVE_FROM_WATCHLIST_START = '[Movie details movie ] REMOVE_FROM_WATCHLIST_START',
  ADD_RATING_START = '[Movie details movie ]ADD_RATING_START',
  REMOVE_RATING_START = '[Movie details movie ] REMOVE_RATING_START',
}

export type SpecificStartActionsTypes =
  | SpecificMovieActionTypes.FETCH_RECOMMENDED_START
  | SpecificMovieActionTypes.FETCH_SIMILAR_START;
